version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
      MYSQL_USER: lab
      MYSQL_SENHA: stock
      MYSQL_HOST: db
      MYSQL_DB: labstock
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_labstock
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: minha_senha_root
      MYSQL_DATABASE: labstock
      MYSQL_USER: lab
      MYSQL_PASSWORD: stock
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    
  nginx:
    image: nginx:alpine
    container_name: nginx_labstock
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  mysql_data:
